#cloud-config
#
# Generated by terraform init/apply. This file is written to the SD card boot
# partition as `user-data`. On first boot Raspberry Pi OS (Bookworm+) runs it
# through cloud-init, which:
#   1. names the host and sets the timezone,
#   2. drops a short-lived GitHub runner registration token on disk,
#   3. optionally enables SSH,
#   4. installs Ansible and runs `ansible-pull` to clone THIS repository and
#      apply the bootstrap playbook that installs + registers the runner.
#
# No SSH or manual login is ever required.

hostname: ${runner_name}
preserve_hostname: false
timezone: ${timezone}
manage_etc_hosts: true

ssh_pwauth: false
disable_root: true

# SSH key if you supplied one (optional debugging; an empty string keeps it off).
ssh_authorized_keys: []

write_files:
  # The short-lived registration token. Read by the github-runner role.
  - path: /etc/pi-actions/registration-token
    permissions: "0600"
    owner: root:root
    content: |
      ${registration_token}
  - path: /etc/pi-actions/environment
    permissions: "0644"
    owner: root:root
    content: |
      PI_ACTION_REPO=${repo_name}
      PI_ACTION_OWNER=${github_owner}

%{ if enable_ssh }
runcmd:
  # Only enable SSH when explicitly requested (debugging).
  - [sh, -c, "systemctl enable --now ssh || true"]
%{ endif }

runcmd:
  - |
    set -eu
    exec >> /var/log/pi-actions-bootstrap.log 2>&1
    export DEBIAN_FRONTEND=noninteractive

    echo "[bootstrap] $(date) Starting Pi Actions bootstrap"

    echo "[bootstrap] $(date) waiting for network"
    for i in $(seq 1 60); do
      if getent hosts github.com >/dev/null 2>&1 || ping -c1 -W2 1.1.1.1 >/dev/null 2>&1; then break; fi
      sleep 2
    done

    echo "[bootstrap] $(date) installing tools"
    for i in 1 2 3; do
      if apt-get update -y && apt-get install -y git ca-certificates curl; then break; fi
      sleep 5
    done

    if ! command -v ansible-pull >/dev/null 2>&1; then
      (apt-get install -y ansible-core 2>/dev/null || apt-get install -y ansible 2>/dev/null) \
        || pip3 install --no-cache-dir --break-system-packages ansible-core
    fi

    echo "[bootstrap] $(date) Cloning + applying bootstrap playbook from ${repo_url}"
    for i in 1 2 3; do
      if ansible-pull \
        -U ${repo_url} \
        -C ${git_branch} \
        -i localhost, \
        --accept-new-host-key \
        -e "${ansible_vars}" \
        ansible/playbooks/bootstrap.yml; then break; fi
      sleep 10
    done

    echo "[bootstrap] $(date) Done. Runner should now register with GitHub."
